### ISSUE TITLE
On iOS, the decrypted String equals the iOS software version

### ISSUE THREAD

**Issue by Peter-717** [shyandsy/cipher2#1]
On iOS, the decrypted returned string is the iOS version of the iPhone. Like iOS 10.3.3
Works fine on Android.
It seems that the plugin is based on swift 2.0. Might be the problem. Could you please update the plugin to be Swift 4.2 compatible? Thanks

**Comment by shyandsy** [comment]
hi, 

thanks for using my plugin.

unfortunately, there is no implementation for ios right now due to the fact i dont have Mac computer for the ios programming.

that will be done before Feb 10, is that ok for you?

**Comment by Peter-717** [comment]
Yes, that's fine. Please let me know if I can be of any assistance (I am using a Mac). I will gladly test your code as soon as possible. Mid-February is really a deadline for me. Thanks again for your quick reply.

**Comment by shyandsy** [comment]
en, there is no any MAC computer on my hand right now

i will try to borrow one and done that as soon as possible

just give me a star after i done that part, thanks:smile:

**Comment by Peter-717** [comment]
I will gladly report when it works on iOS and give you a BIG star!

**Comment by Peter-717** [comment]
Have you checked: https://github.com/krzyzanowskim/CryptoSwift
Please look at their AES example, it sounds like a swift call like the one that follows could be the answer. What do you think?
    let decrypted = try AES(key: key, blockMode: CBC(iv: iv), padding: .pkcs7).decrypt(encrypted)

**Comment by shyandsy** [comment]
@Peter-717 

I created a macos system on vmware yesterday, and finished the ios support today.

it works now, just try it

**Comment by Peter-717** [comment]
Thank you so much.

Excuse my lack of knowledge. But how do import the CryptoSwift Library?

I get a “No such module CryptoSwift” in Xcode when running the code.

THANKS!!!

**Comment by Peter-717** [comment]
Got it to work by doing the following:
- Following the Installation steps explained within https://github.com/krzyzanowskim/CryptoSwift
- Then editing Podfile an adding pod 'CryptoSwift' and running pod install on the terminal
- Then back to Xcode and Run - Voila!
Thank you so much again!

**Comment by Peter-717** [comment]
Just noticed that the App will crash if the decrypted provided string isn't of 24 characters exactly.

**Comment by Peter-717** [comment]
Actually a bit worse than that. If the decryption fails (for any reason), the App crashes silently (no error is thrown)

**Comment by shyandsy** [comment]
@Peter-717 
the exmaple code in the plugin works good on my machine

could u give a sample input for crash?

for now, i haven't do input data validate in the plugin, and you have to check the input data before call the method. i will add the validation code later

**Comment by shyandsy** [comment]
@Peter-717 
en, it should add CryptoSwift Library by itself

why u need to add CryptoSwift Library>?

**Comment by Peter-717** [comment]
The code works good on my machine too, when the string to be decrypted is a “valid” encrypted string. 

As soon as you provide any other string like ‘Hello’ for being decrypted, the App crashes silently :( no error message printed on the console.

**Comment by Peter-717** [comment]
Please try to run the following code:
class _MyHomePageState extends State<MyHomePage> {

  String plainText = '我是shyandsy，never give up man';
  String key = 'xxxxxxxxxxxxxxxx';
  String iv = 'yyyyyyyyyyyyyyyy';

  String encryptedString;

  String decryptedString;


  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    _encrypt();
  }

  Future<Null> _encrypt() async {
    encryptedString = await Cipher2.encryptAesCbc128Padding7(plainText, key, iv);
    print(encryptedString);
  }

 Future<Null> _decrypt() async {

    decryptedString = await Cipher2.decryptAesCbc128Padding7(encryptedString, key, iv);

    print(decryptedString);
    encryptedString = 'Hello';

    decryptedString = await Cipher2.decryptAesCbc128Padding7(encryptedString, key, iv);

    print(decryptedString);

  }

The App crashes as soon as it tries to decrypt the string 'Hello'. 
Hope this helps. Thanks!

**Comment by shyandsy** [comment]
obviously hello is not a valid encrypted string

its aes 128 pkcs padding 7, u should pass a base64 encode string with n times 128bit length

发自我的 iPhone

> 在 2019年1月22日，21:06，Peter-717 <notifications@github.com> 写道：
> 
> The code works good on my machine too, when the string to be decrypted is a “valid” encrypted string. 
> 
> As soon as you provide any other string like ‘Hello’ for being decrypted, the App crashes silently :( no error message printed on the console.
> 
> 
>

**Comment by Peter-717** [comment]
I agree with you, but the problem is that you can not know in advance whether the String you’re provided with meets these criteria. On the Android side, if you provide ‘Hello’ to the Decrypter method, it rightly returns an error, but doesn’t crash the app.

**Comment by shyandsy** [comment]
i agree with u and i will add input check later

发自我的 iPhone

**Comment by Peter-717** [comment]
Thanks! Can’t wait - We’re so close now :)

**Comment by shyandsy** [comment]
finished the exception part for ios

will push code after modification on android today

发自我的 iPhone

> 在 2019年1月22日，23:03，Peter-717 <notifications@github.com> 写道：
> 
> Thanks! Can’t wait - We’re so close now :)
>

**Comment by shyandsy** [comment]
@Peter-717 
the new version 0.2.0 published

the exception can be handled for both ios and android

https://pub.dartlang.org/packages/cipher2

**Comment by Peter-717** [comment]
Awesome! I’ll give it a try tomorrow.
Thanks!

**Comment by shyandsy** [comment]
welcome

i also need this code for my project

and i will support the other mode of aes, and other encryption method later



发自我的 iPhone

> 在 2019年1月23日，22:08，Peter-717 <notifications@github.com> 写道：
> 
> Awesome! I’ll give it a try tomorrow.
> Thanks!
> 
>

**Comment by shyandsy** [comment]
@Peter-717 any feedback?

**Comment by Peter-717** [comment]
Works great now on both iOS and Android - Thanks!
