### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Ljava/util/Base64;

### ISSUE THREAD

**Issue by eavesmy** [shyandsy/cipher2#19]
![image](https://user-images.githubusercontent.com/14216176/60804536-58582b00-a1b0-11e9-8441-2da91cdc0d12.png)
![image](https://user-images.githubusercontent.com/14216176/60804579-6e65eb80-a1b0-11e9-8974-ee8d69c60638.png)

请问下这个怎么解决？

**Comment by shyandsy** [comment]
u should learn about how to ask a question
